- target: out/dev
  values:
    env: dev
    app:
      replicas: 1
    debug: true
  strip:
    - .tpl

- target: out/staging
  values:
    env: staging
    app:
      replicas: 2
  strip:
    - .tpl

- target: out/prod
  values:
    env: prod
    app:
      replicas: 4
  strip:
    - .tpl